// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlb

var TableNames = struct {
	Accounts       string
	JWTSignKeys    string
	OidcClients    string
	OidcSecrets    string
	PasswordAuthns string
}{
	Accounts:       "accounts",
	JWTSignKeys:    "jwt_sign_keys",
	OidcClients:    "oidc_clients",
	OidcSecrets:    "oidc_secrets",
	PasswordAuthns: "password_authns",
}
