// Code generated by ogen, DO NOT EDIT.
package api

type HealthRes interface {
	healthRes()
}

type IdpSigninRes interface {
	idpSigninRes()
}

type IdpSignupRes interface {
	idpSignupRes()
}

type OpAuthorizeRes interface {
	opAuthorizeRes()
}

type OpCallbackRes interface {
	opCallbackRes()
}

type OpCertsRes interface {
	opCertsRes()
}

type OpLoginRes interface {
	opLoginRes()
}

type OpLoginViewRes interface {
	opLoginViewRes()
}

type OpOpenIDConfigurationRes interface {
	opOpenIDConfigurationRes()
}

type OpRevokeRes interface {
	opRevokeRes()
}

type OpTokenRes interface {
	opTokenRes()
}

type OpUserinfoRes interface {
	opUserinfoRes()
}

type RpCallbackRes interface {
	rpCallbackRes()
}

type RpLoginRes interface {
	rpLoginRes()
}
